frontend:
    @echo Installing frontend
catalcogue:
    @echo Installing catalcogue
cart:
    @echo Installing cart
user:
    @echo Installing user
shipping:
    @echo Installing shipping
payment:
    @echo Installing payment
mongodb:
    @echo Installing mongodb
redis:
    @echo Installing redis
mysql:
    @echo Installing mysql
rabbitmq:
    @echo Installing rabbitmq

