frontend:
    @echo Installing Frontend:
catalogue:
    @echo Installing Catalogue:
cart:
    @echo Installing Cart:
user:
    @echo Installing User:
shipping:
    @echo Installing Shipping:
payment:
    @echo Installing Payment:
mongodb:
    @echo Installing Mongodb:
redis:
    @echo Installing Redis:
mysql:
    @echo Installing Mysql:
rabbitmq:
    @echo Installing Rabbitmq:

